# Generated by Django 4.2.4 on 2023-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
